const path=require('node:path'),fs=require('node:fs'),test=require('node:test'),assert=require('node:assert/strict'),YAML=require('yaml');
const {loadTs}=require('../tools/runtime.cjs'),root=path.resolve(__dirname,'..'),load=n=>loadTs(path.join(root,'src',n+'.ts'));
const {createOpening}=require('./numerical-fixture.cjs');
const {applyCommand}=load('engine'),{acceptNarrativeUpdate}=load('mvu-policy');
const {projectPromptState}=load('prompt-view'),{formatPromptView}=load('prompt-format');
const {repairIssues,repairPrompt,applyRepairPatch}=load('variable-repair'),{evolutionOptions}=load('progression');
const {normalizeOperations}=load('operation-input'),{bindWorldbook}=require('../tools/worldbook.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
const start=()=>createOpening({mode:'默认'},'systems');
const run=(s,op,id='step-'+s.stat_data._结算.状态版本)=>applyCommand(s,{...op,id,branchId:'systems',expectedVersion:s.stat_data._结算.状态版本},()=>.5).session;
const acquire=(profile='技艺',actorId='player',id='learned')=>({kind:'acquire',actorId,abilityId:id,name:'潮汐研习',grade:'精良',source:'学习',evidence:'完成导师布置的练习并展示成果',description:'辨认潮路与水流变化',trigger:'观察水流',limitations:'需要接触现场',profile,mechanism:'cold',power:1,capacity:20,cost:2,cooldown:5});
test('开放进化由实际能力生成方案，可组合新结构并实际使用，确认后才改变快照',()=>{
 const {evolutionPrompt,parseEvolution}=load('evolution-generation'),{editSession}=load('settlement');
 let s=run(start(),acquire());s.stat_data._能力.learned.等级=5;
 const design={name:'潮纹折光',principle:'以水流的局部折射建立定向成像',evidence:'反复观察水流并完成玻璃海实践',description:'读取水面折射并聚成短暂定向光束',trigger:'存在可观察的水面',limitations:'成像需要稳定水面，强风会打散焦点',cost:3,cooldown:4,utility:{bonus:2},strike:{mechanism:'refraction',power:1.3,fixed:2,seconds:3}};
 const proposals=parseEvolution(JSON.stringify([{direction:'折射成像',design}]));
 assert(!evolutionPrompt(s.stat_data,'learned','聚焦水光')[0].content.includes('容纳'));
 const op={kind:'evolution',abilityId:'learned',...proposals[0],base:clone(s.stat_data)};
 const evolved=editSession(s,op);
 assert.equal(s.stat_data._能力.learned.名称,'潮汐研习');
 assert.equal(evolved.stat_data._能力.learned.名称,'潮纹折光');
 assert.equal(evolved.stat_data._能力.learned.品阶,'稀有');
 assert.equal(evolved.stat_data._能力.learned.等级,5);
 assert(evolved.stat_data._能力.learned.成长记录['evolve-1'].includes('折射'));
 const encounter=run(evolved,{kind:'encounter',name:'对手',tier:'普通',mechanism:'cold'});
 const foe=Object.keys(encounter.stat_data._实体).find(id=>id.startsWith('enc-'));
 const attacked=run(encounter,{kind:'strike',actorId:'player',targetId:foe,abilityId:'learned'});
 assert(attacked.stat_data._实体[foe].生命.当前<60);
 assert.equal(attacked.stat_data._实体.player.资源.energy.当前,47);
 assert.throws(()=>editSession(evolved,op),/存档已变化/);
 assert.throws(()=>run(s,{kind:'evolve',abilityId:'learned',direction:'任意空名'}),/design/);
});
test('通用转化释放和技艺检定执行资源与冷却，失败保留原存档',()=>{
 let s=run(start(),acquire('转化'));
 s=run(s,{kind:'exposure',source:'寒雾',mechanism:'cold',mechanismName:'低温',amount:15,conditions:'接触低温水汽'});
 const before=clone(s);s=run(s,{kind:'channel',abilityId:'learned',amount:5,purpose:'冷却容器'});
 assert.equal(s.stat_data._实体.player.资源.energy.当前,48);
 assert.equal(s.stat_data._实体.player.资源.learned.当前,10);
 assert.throws(()=>run(s,{kind:'channel',abilityId:'learned',amount:1,purpose:'再次冷却'}),/冷却/);
 assert.equal(before.stat_data._实体.player.资源.learned.当前,15);
 let utility=run(start(),acquire());utility=run(utility,{kind:'check',actorId:'player',abilityId:'learned',difficulty:15,task:'辨认潮流'});
 assert.equal(utility.stat_data._实体.player.资源.energy.当前,48);
 assert.throws(()=>run(utility,{kind:'check',actorId:'player',abilityId:'learned',difficulty:15,task:'再次辨认'}),/冷却/);
 const optional=acquire();for(const key of ['mechanism','cost','cooldown','power','capacity'])delete optional[key];
 assert.equal(run(start(),optional).stat_data._能力.learned.冷却本地秒,0);
});
test('AI可读时间与界面历法一致，最近死因和任务保持可见',()=>{
 const {formatGameTime}=load('game-time');const s=start().stat_data;
 s._时空.位面目录.main.时钟.历法={名称:'潮历',元年:8,每月天数:[7,11],每天小时:9,每小时分钟:30,每分钟秒:40};
 s._时空.起源时刻秒=98765;
 const schema=load('schema').Schema;
 s._任务.q=schema.shape._任务.unwrap().valueType.parse({名称:'潮路调查',状态:'进行中',描述:'查清旧潮路断裂的位置'});
 s._死亡记录.d=schema.shape._死亡记录.unwrap().valueType.parse({因果链:{a:{机制ID:'cold',作用条件:'冰雾包围',直接致死:true}},授予能力ID:{learned:true}});
 const output=formatPromptView(projectPromptState(s)),date=formatGameTime(s,'main');
 assert(output.includes(date.date+' '+date.time));assert(output.includes('潮路调查'));assert(output.includes('冰雾包围'));
});
test('开局资料按实际经历调用，越界与首次规则互不混入',async()=>{
 const file=bindWorldbook(fs.readFileSync(path.join(root,'世界书/控制器/EJS开局控制器.txt'),'utf8'),'本卡');
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 const execute=async(state)=>{const calls=[];await new AsyncFunction('getvar','getwi','print',file.slice(file.indexOf('<%')+2,file.lastIndexOf('%>')))(()=>state,async(...args)=>{calls.push(args);return '';},()=>{});return calls;};
 assert.deepEqual(await execute(start().stat_data),[]);
 const original=load('opening').createOpening({mode:'默认'},'new-opening').stat_data;
 assert.deepEqual(await execute(original),[['本卡','开局_初次归泊'],['本卡','能力_越界']]);
 original.叙事.首次资料完成=true;
 assert.deepEqual(await execute(original),[['本卡','能力_越界']]);
 for(const file of ['系统/行动与结算.txt','玩法/起源涅槃/死亡与复苏.yaml','变量/变量更新规则_首次.yaml'])assert(!fs.readFileSync(path.join(root,'世界书',file),'utf8').includes('越界'));
 assert(!fs.readFileSync(path.join(root,'世界书/角色/末墟.yaml'),'utf8').includes('车祸'));
});
test('学习获得技艺可运用、训练、进化，时间资源与重放一致',()=>{
 let s=run(start(),acquire());assert.equal(s.stat_data._能力.learned.来源.类型,'学习');
 s=run(s,{kind:'use',actorId:'player',abilityId:'learned',purpose:'辨认河流方向'});
 assert.equal(s.stat_data._实体.player.资源.energy.当前,48);
 assert.throws(()=>run(s,{kind:'use',actorId:'player',abilityId:'learned',purpose:'立即重复'}),/冷却/);
 s=run(s,{kind:'train',actorId:'player',abilityId:'learned',seconds:14400,focus:'对照潮路图练习判断'});
 s=run(s,{kind:'train',actorId:'player',abilityId:'learned',seconds:15000,focus:'校核不同潮位下的判断'});
 s=run(s,{kind:'train',actorId:'player',abilityId:'learned',seconds:600,focus:'完成最后一组观察记录'});
 const a=s.stat_data._能力.learned;assert.equal(a.等级,5);assert.equal(a.熟练度,0);
 assert(evolutionOptions(s.stat_data,'player','learned').some(o=>o.direction==='精通'));
 s=run(s,{kind:'evolve',abilityId:'learned',direction:'精通'});assert.equal(s.stat_data._能力.learned.品阶,'稀有');
 assert.equal(s.stat_data._能力.learned.效果.utility.参数.检定加值,1);
 const event=Object.values(s.death_adaptation_runtime.events).at(-1);
 assert.equal(applyCommand(s,event.command,()=>{throw Error('重复随机');}).replayed,true);
 assert.throws(()=>run(s,acquire()),/已登记/);
});
test('任何实体可获得攻击能力；非死亡转化能力实际吸收并释放',()=>{
 let s=run(start(),{kind:'encounter',name:'访客',tier:'普通',mechanism:'cold'});
 s=run(s,{...acquire('攻击','enc-step-0','npc-skill'),cost:0});
 assert.equal(s.stat_data._实体['enc-step-0'].能力ID['npc-skill'],true);
 s=run(s,{...acquire('转化'),cost:0,cooldown:0});
 s=run(s,{kind:'exposure',source:'寒雾',mechanism:'cold',mechanismName:'低温',amount:15,conditions:'寒雾接触身体'});
 assert.equal(s.stat_data._实体.player.生命.当前,100);assert.equal(s.stat_data._实体.player.资源.learned.当前,15);
 s=run(s,{kind:'channel',abilityId:'learned',amount:10,purpose:'降低小容器温度'});
 assert.equal(s.stat_data._实体.player.资源.learned.当前,5);
});
test('11项JSON字符串动作归一化为实际对象；自然语言动作保留供局部修复',()=>{
 const s=start(),ops=Array.from({length:11},()=>JSON.stringify({kind:'advance',seconds:'1'}));
 const input={...clone(s.stat_data),叙事:{...clone(s.stat_data.叙事),本轮时间:0,本轮结算:ops}};
 const after=acceptNarrativeUpdate(s.stat_data,input);assert.equal(after._时空.起源时刻秒,11);
 assert.deepEqual(clone(normalizeOperations(normalizeOperations(ops))),clone(normalizeOperations(ops)));
 input.叙事.本轮结算=Array.from({length:11},()=> '时间前进');
 s.stat_data._待修复={版本:0,输入:input,原因:'expected object received string'};
 const issues=repairIssues(s.stat_data);assert.equal(issues.length,1);assert.equal(issues[0].路径,'/叙事/本轮结算/操作');
 const prompt=JSON.parse(repairPrompt(s.stat_data,'经过11秒。','')[1].content);
 assert(prompt.相关操作结构.includes('advance:'));assert(prompt.相关操作结构.includes('seconds'));
 const repaired=applyRepairPatch(s,[{op:'replace',path:issues[0].路径,value:[{kind:'advance',seconds:11}]}]);
 assert.equal(repaired.stat_data._时空.起源时刻秒,11);
});
test('实际EJS状态输出为可读分段，保留判定精度和人物信息',async()=>{
 const s=start().stat_data;const view=projectPromptState(s),text=formatPromptView(view);
 assert(text.includes('当前世界:'));assert(text.includes('能力:'));assert(text.includes('起源涅槃'));assert(!text.includes('规则ID'));
 assert(!text.match(/0\.\d{6}/));assert(!text.includes('能力授予状态'));assert.equal(view.本轮骰列.length,32);
 const ejs=fs.readFileSync(path.join(root,'世界书/变量/变量列表.txt'),'utf8'),out=[];
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 await new AsyncFunction('getvar','getChatMessages','print',ejs.slice(ejs.indexOf('<%')+2,ejs.lastIndexOf('%>')))(()=>s,()=>[],v=>out.push(v));
 assert.equal(out.join(''),text);
 fs.mkdirSync(path.join(root,'build/verification'),{recursive:true});
 fs.writeFileSync(path.join(root,'build/verification/实际状态提示词.txt'),out.join(''));
});
test('世界书按范围预留顺序；EJS成长按情境加载关闭规则',async()=>{
 const entries=YAML.parse(fs.readFileSync(path.join(root,'世界书条目清单.yaml'),'utf8')).条目;
 for(const pos of ['角色定义之前','角色定义之后','指定深度']){
  const nums=entries.filter(e=>e.启用 && e.插入位置.类型===pos).map(e=>e.插入位置.顺序);assert.equal(new Set(nums).size,nums.length);
 }
 assert(entries.find(e=>e.名称==='品阶').插入位置.顺序>1000);
 assert.equal(entries.find(e=>e.名称==='能力进化').启用,false);
 const file=fs.readFileSync(path.join(root,'世界书/控制器/EJS成长控制器.txt'),'utf8'),compiled=bindWorldbook(file,'本卡');
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 const execute=async(message)=>{const calls=[];await new AsyncFunction('getvar','getChatMessages','getwi','print',compiled.slice(compiled.indexOf('<%')+2,compiled.lastIndexOf('%>')))(()=>start().stat_data,()=>[{message}],async(...args)=>{calls.push(args);return '';},()=>{});return calls;};
 assert.deepEqual(await execute('打招呼'),[]);
 assert.deepEqual(await execute('训练技艺'),[['本卡','熟练度与等级']]);
 assert.deepEqual(await execute('选择进化'),[['本卡','熟练度与等级'],['本卡','能力进化']]);
});
