export const Schema = z.object({
  初始化完成: z.boolean().prefault(false),
  R18模式: z.boolean().prefault(false),

  世界: z.object({
    当前时间: z.string().prefault(''),
    周几: z.string().prefault(''),
    天气: z.string().prefault(''),
  }).prefault({}),

  主角: z.object({
    姓名: z.string().prefault(''),
    性别: z.string().prefault(''),
    年龄: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    种族: z.string().prefault(''),
    喜好: z.string().prefault(''),
    厌恶: z.string().prefault(''),
    外貌特征: z.string().prefault(''),
    基础体型: z.string().prefault(''),
    神态: z.string().prefault(''),
    特征: z.string().prefault(''),
    天赋能力: z.string().prefault(''),
    财富: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    境界: z.string().prefault('凡人'),
    战力: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    当前地点: z.object({
      位面: z.string().prefault(''),
      大陆: z.string().prefault(''),
      城市: z.string().prefault(''),
      区域: z.string().prefault(''),
      场景: z.string().prefault(''),
      具体位置: z.string().prefault(''),
    }).prefault({}),
    服装: z.object({
      上衣: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      内衣: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      下装: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      内裤: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      袜子: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      鞋子: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
    }).prefault({}),
    随身物品: z.record(z.string(), z.object({
      描述: z.string().prefault(''),
      数量: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
      品阶: z.string().prefault(''),
      能力: z.string().prefault(''),
    })).prefault({}),
    人际关系: z.record(z.string(), z.string()).prefault({}),
  }).prefault({}),

  角色名录: z.record(z.string(), z.object({
    姓名: z.string().prefault(''),
    身份: z.string().prefault(''),
    性别: z.string().prefault(''),
    年龄: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    来源世界: z.string().prefault(''),
    种族: z.string().prefault(''),
    喜好: z.string().prefault(''),
    厌恶: z.string().prefault(''),
    外貌特征: z.string().prefault(''),
    基础体型: z.string().prefault(''),
    神态: z.string().prefault(''),
    特征: z.string().prefault(''),
    天赋能力: z.string().prefault(''),
    财富: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    境界: z.string().prefault('凡人'),
    战力: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
    好感度: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v).transform(v => _.clamp(v, 0, 100)),
    当前地点: z.object({
      位面: z.string().prefault(''),
      大陆: z.string().prefault(''),
      城市: z.string().prefault(''),
      区域: z.string().prefault(''),
      场景: z.string().prefault(''),
      具体位置: z.string().prefault(''),
    }).prefault({}),
    服装: z.object({
      上衣: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      内衣: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      下装: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      内裤: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      袜子: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      鞋子: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
    }).prefault({}),
    随身物品: z.record(z.string(), z.object({
      描述: z.string().prefault(''),
      数量: z.coerce.number().prefault(0).transform(v => _.isNaN(v) || !_.isFinite(v) ? 0 : v),
      品阶: z.string().prefault(''),
      能力: z.string().prefault(''),
    })).prefault({}),
    人际关系: z.record(z.string(), z.string()).prefault({}),
    nsfw档案: z.object({
      初次存在与否: z.boolean().prefault(true),
      性对象: z.string().prefault(''),
      是否怀孕: z.boolean().prefault(false),
      子嗣列表: z.string().prefault(''),
      三围: z.object({
        胸围: z.coerce.number().prefault(0),
        腰围: z.coerce.number().prefault(0),
        臀围: z.coerce.number().prefault(0),
      }).prefault({}),
      罩杯: z.string().prefault(''),
      胸型: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
      户型: z.object({ 名称: z.string().prefault(''), 描述: z.string().prefault(''), 状态: z.string().prefault('') }).prefault({}),
    }).prefault({}),
  })).prefault({}),
});

export type Schema = z.output<typeof Schema>;
